### ISSUE TITLE
[BUG] Loading Dockerhub image

### ISSUE THREAD

**Issue by NotYuSheng** [pluja/whishper#114]
## **Description**
Received error when running the Docker image

```
Error: The directory named as part of the path /var/log/whishper/transcription.out.log does not exist in section 'program:transcription' (file: '/etc/supervisor/conf.d/supervisord.conf')
For help, use /usr/bin/supervisord -h
```

[Whishper image](https://hub.docker.com/layers/pluja/whishper/latest/images/sha256-a54b82c63e79340e2ee0edd5d6d29ab97b26f4367f19757493897e28be5f1d2d?context=explore)

[Docker hub](https://hub.docker.com/r/pluja/whishper)

### **To Reproduce**
1. docker pull pluja/whishper
2. docker run --name whishper pluja/whishper:latest

### **Expected behavior**
App to start normally

### Environment
- OS: Windows
- Version: pluja/whishper:latest
- Index digest: sha256:20bd629fe7d83f1369709412eb4376191806050e66ea0f8193615d27cb22edec

## Logs and Configuration
```
Error: The directory named as part of the path /var/log/whishper/transcription.out.log does not exist in section 'program:transcription' (file: '/etc/supervisor/conf.d/supervisord.conf')
For help, use /usr/bin/supervisord -h
```

**Comment by endimionzf** [comment]
Any update? I have the same problem

**Comment by NotYuSheng** [comment]
I don't think the intend is for users to pull the image and run directly independently.
