### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by zZeleZz** [pluja/whishper#16]
Hi!
OS Ubuntu

After launching "docker compose up", the following error appears:
whisper-libretranslate  | PermissionError: [Errno 13] Permission denied: '/home/libretranslate/.local/share/argos-translate'

There is also such a message in the logs:
whisper-api             | ValueError: model must be one of ['tiny', 'tiny.en', 'small', 'small.en', 'base', 'base.en', 'medium', 'medium.en', 'large-v2']

![image](https://github.com/pluja/whishper/assets/99475797/98b59ff1-d219-4ab6-b129-fe3746035331)

**Comment by pluja** [comment]
You need to `chown -R 1032:1032 whishper_data/libretranslate` so libretranslate can write there. Check step 3: https://whishper.net/guides/install/#manual-install

**Comment by zZeleZz** [comment]
Nnow only such a mistake
![image](https://github.com/pluja/whishper/assets/99475797/fd90d107-9d57-4f1a-b882-500489bb5d84)

**Comment by pluja** [comment]
seems like you used a wrong value for the whisper models?
