### ISSUE TITLE
Windows Runtime Support with Docker.

### ISSUE THREAD

**Issue by joramirez764** [pluja/whishper#18]
Currently, Whishper is designed to run on Unix/Linux systems, which can make it difficult to use in Windows environments. I propose to enable support for running Whishper on Windows via Docker so that more users can enjoy this application on different platforms.

Proposed Changes:** ** Proposed Changes:** Proposed Changes:** Proposed Changes:** Proposed Changes:** Proposed Changes
- Adapt the configuration scripts to work in Windows environments using Docker.
- Provide clear instructions for Windows users on how to use Docker to run Whishper.

Expected Benefits:** Expected Benefits:** Expected Benefits:** Expected Benefits:** Expected Benefits:** Expected Benefits:** Expected Benefits
- Increased accessibility of Whishper for Windows users.
- Expanded user base and potential contributors.

**Suggested Steps:** 1.
1. Adapt the installation and configuration scripts to be Windows compatible.
2. Document the requirements and steps needed to run Whishper on Windows using Docker.
3. Perform extensive testing in Windows environments to ensure proper functionality.

I hope this enhancement will make Whishper more accessible and useful to a wider audience, including Windows users.

**Comment by pluja** [comment]
Hi, I would like to complete this issue, yet I don't really know what is needed since I don't use windows on any of my computers. If you know how should I proceed or what changes need to be done, you can open a new PR or guide me in this issue here.

**Comment by johnwayne087** [comment]
I rewrote the SH file for windows as a bat file. Ran it and it works just fine so far.

`@echo off

rem Check if Docker is installed
docker --version >nul 2>&1
if %errorlevel% neq 0 (
  echo Docker is not installed. Please install Docker first.
  goto :EOF
)

rem Ask for setup directory
echo Do you want to set up everything in the current directory? (Y/N)
set /p answer=
if /i "%answer%"=="Y" (
  echo Setting up everything in the current directory
) else (
  echo Enter the name of the directory where you want to set up everything:
  set /p directory=
  echo Setting up everything in the %directory% directory
  md "%directory%"
  cd "%directory%"
)

rem Get docker-compose.yml
echo Getting the docker-compose.yml file from Github
curl -o docker-compose.yml https://raw.githubusercontent.com/pluja/whishper/main/docker-compose.yml

rem Get nginx.conf
echo Getting the nginx.conf file from Github 
curl -o nginx.conf https://raw.githubusercontent.com/pluja/whishper/main/nginx.conf

rem Get .env file
if exist .env (
  echo .env file already exists
  echo Do you want to overwrite it? (Y/N)
  set /p answer=
  if /i "%answer%"=="Y" (
    echo Copying env.example to .env
    curl -o .env https://raw.githubusercontent.com/pluja/whishper/main/example.env
  )
) else (
  echo Getting the default .env file from Github
  curl -o .env https://raw.githubusercontent.com/pluja/whishper/main/example.env
)

rem Create directories
echo Creating necessary directories for libretranslate
md whishper_data\libretranslate\data
md whishper_data\libretranslate\cache

rem Pull images
echo Do you want to pull docker images? (Y/N) 
set /p answer=
if /i "%answer%"=="Y" (
  echo Pulling docker images
  docker-compose pull
)

rem Start containers
echo Do you want to start the containers? (Y/N)
set /p answer=
if /i "%answer%"=="Y" (
  echo Starting whishper...
  docker-compose up -d
)`

**Comment by pluja** [comment]
@johnwayne087 that's awesome, thank you! I will add it soon :)

**Comment by pluja** [comment]
@johnwayne087 can you confirm the script provided by @johnwayne087 is working for you too? If so, I will add it and update the documentation!

**Comment by pluja** [comment]
@joramirez764  can you confirm the script provided by @johnwayne087 is working for you too? If so, I will add it and update the documentation!

**Comment by djzigoh** [comment]
> @joramirez764 can you confirm the script provided by @johnwayne087 is working for you too? If so, I will add it and update the documentation!

Yes it works!!!  / tested in windows 11 with docker

**Comment by pluja** [comment]
Awesome, I'll be adding it this week

**Comment by pluja** [comment]
@johnwayne087 I've added your script in the latest commit 6bc73dfd83d1ccce49e7d0745828516cc2fd21e9

**Comment by TheRedSpy15** [comment]
I keep getting this error when trying to run the script:
```
ParserError: C:\Users\hjada\Documents\whishper\get-whishper.ps1:1
Line |
   1 |  @echo off
     |        ~~~
     | Unexpected token 'off' in expression or statement.
```

**Comment by ismailkhan-dev** [comment]
> I keep getting this error when trying to run the script:
> 
> ```
> ParserError: C:\Users\hjada\Documents\whishper\get-whishper.ps1:1
> Line |
>    1 |  @echo off
>      |        ~~~
>      | Unexpected token 'off' in expression or statement.
> ```

Convert the .ps1 file into a .bat file then run the .bat file in command prompt not powershell session. It should work like that. I'm sure there's some powershell commands where you can run a ps1 file as a bat file in a powershell session but this is what I did. It works for me this way.
