### ISSUE TITLE
Support for more languages

### ISSUE THREAD

**Issue by tobsowo** [pluja/whishper#19]
I'll like to have additional language especially related to Africa - IG, YO, HA and more.

Is there a way to achieve this?
https://en.m.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by pluja** [comment]
Hi, supported languages are limited to `Whisper` model languages. If the language is supported by whisper, and is not listed in whishper, I can surely add it.

**Comment by tobsowo** [comment]
Just checked seems there's no support yet.
