### ISSUE TITLE
macOS LibreTranslate permissions problem

### ISSUE THREAD

**Issue by hundehausen** [pluja/whishper#2]
If I use the command 
`chown 1032:1032 whishper_data/libretranslate`

The containers do not start. If I leave the folder creation with default rights and permissions, they start.

Latest macOS and latest Docker version

**Comment by pluja** [comment]
Hi, thank you for reporting. I wasn't able to test on macOS. Without the `chown`, does the LibreTranslate container show any error or warning in the logs? Does the translation work fine?

**Comment by hundehausen** [comment]
Yes, everything is working fine as expected.

**Comment by pluja** [comment]
Nice, I'll add a note on the docs about this later

**Comment by pluja** [comment]
@hundehausen Could you share the error you get when the permissions are set? And do you know why this happens on macOS? Is it because of the way Docker runs on macOS?

**Comment by pluja** [comment]
@hundehausen I made a change to the `get-whishper.sh` script, could you try running it and see if it works on your macOS?

**Comment by hundehausen** [comment]
I ran the script:
```
Do you want to pull docker images? (y/n)
n
Do you want to start the containers? (y/n)
y
Starting whishper...
[+] Running 5/7
 ✔ Network whishper_default          Created                                                                            0.0s 
 ⠿ Container whisper-api             Starting                                                                           0.4s 
 ⠿ Container whishper-mongo-1        Starting                                                                           0.4s 
 ✔ Container whisper-libretranslate  Started                                                                            0.4s 
 ✔ Container whishper-web            Created                                                                            0.0s 
 ✔ Container whishper-backend        Created                                                                            0.0s 
 ✔ Container whishper-nginx-1        Created                                                                            0.0s 
Error response from daemon: error while creating mount source path '/host_mnt/Users/hundehausen/Coding/whishper/whishper_data/whisper_models': mkdir /host_mnt/Users/hundehausen/Coding/whishper/whishper_data/whisper_models: operation not permitted
```

**Comment by pluja** [comment]
Huh, could it be that the directory already existed? Did you detect what was causing this problem? Were you able to manually bring all containers up?

**Comment by hundehausen** [comment]
I tried again:

1. pulled latest commits
2. pulled newest images manualy
3. deleted the folder _whishper_data_ recursively
4. ran get-whisper.sh

`❯ ./get-whishper.sh
Do you want to set up everything in the current directory? (y/n)
y
Setting up everything in the current directory
Getting the docker-compose.yml file from Github
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2778  100  2778    0     0  10324      0 --:--:-- --:--:-- --:--:-- 10562
Getting the nginx.conf file from Github
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   702  100   702    0     0   3921      0 --:--:-- --:--:-- --:--:--  4057
.env file already exists
Do you want to overwrite it? (y/n)
n
Creating necessary directories for libretranslate
Setting permissions for libretranslate
macOS detected... Leaving permissions as is.
Do you want to pull docker images? (y/n)
n
Do you want to start the containers? (y/n)
y
Starting whishper...
[+] Running 5/7
 ✔ Network whishper_default          Created                                                                            0.0s 
 ⠿ Container whishper-mongo-1        Starting                                                                           0.6s 
 ⠿ Container whisper-api             Starting                                                                           0.6s 
 ✔ Container whisper-libretranslate  Started                                                                            0.6s 
 ✔ Container whishper-web            Created                                                                            0.0s 
 ✔ Container whishper-backend        Created                                                                            0.0s 
 ✔ Container whishper-nginx-1        Created                                                                            0.0s 
Error response from daemon: error while creating mount source path '/host_mnt/Users/hundehausen/Coding/whishper/whishper_data/uploads': mkdir /host_mnt/Users/hundehausen/Coding/whishper/whishper_data/uploads: operation not permitted`

I got

**Comment by hundehausen** [comment]
I don't get the error, if I do not use the script and just use `docker compose up` or `docker-compose up`.
Maybe, because I run the script with `sudo` the folder gets created with the root user and this is why the container can not access it.
The folder gets created automatically, there is no need to do it manually in the script, at least on macOS.

**Comment by hundehausen** [comment]
But I haven't tested libretranslate yet. I'll just do that right now.

**Comment by hundehausen** [comment]
Yes, everything works fine. I think there is no need to create a folder and set any permissions on macOS.

**Comment by pluja** [comment]
Ok, thank you, I will update the docs accordingly then.
