### ISSUE TITLE
[Feature] Show progress on uploads and transcriptions

### ISSUE THREAD

**Issue by tobsowo** [pluja/whishper#20]
Thank you for this wonderful and useful tool.

I noticed when a file is uploaded, there's no action show on the home screen making seems like nothing was uploaded until after like a minute it starts showing processing.

Secondly, processing takes long I guess depending on file size but if there can be a counter that show percentage completed, maybe a circle on the right with percentage number inside, it will help to know how soon the processing will be completed.

BTW, the counter can also works for uploading too before the processing starts.

Thank you so much for this great software.

**Comment by pluja** [comment]
This would be a great feature, however it is not now in the list of my priorities for whishper, and I'm not sure how this would be implemented... If anyone wants to contribute with a PR implementing this, it will be very welcome.

**Comment by pluja** [comment]
This is now implemented in [v3](https://github.com/pluja/whishper/releases/tag/v3.0.0)

**Comment by tobsowo** [comment]
Thank you.
I just tried it but it seems not to work for me.
I have repulled the containers twice.

**Comment by pluja** [comment]
You must update the docker-compose or reinstall using the get-whishper.sh script. Please take a look at the release page. Containers have changed in v3.

**Comment by tobsowo** [comment]
Yes, I reinstalled using script and it overwrite existing container and .env files.

**Comment by pluja** [comment]
Are you uploading a big enough file? Small files upload so fast it doesn't show up.

**Comment by tobsowo** [comment]
Yes, see link here https://vts. bluespace. ng

**Comment by pluja** [comment]
@tobsowo I deleted your comment, so your URL is not visible here for anyone to use. I have tested your instance, and it seems like there's some major problem. Transcriptions can't be deleted, editing them can't save, etc. Are you sure your setup is correct for your public domain? Can you explain how did you set it up?

**Comment by pluja** [comment]
On a local install, it is working fine for me:
![image](https://github.com/pluja/whishper/assets/64632615/2043e5f9-da36-4341-998e-1ebfe244eb3c)

**Comment by tobsowo** [comment]
Thank you for deleting. BTW, possible to have a login page for future releases?

I installed using the script and nothing else was done.

**Comment by pluja** [comment]
Did you configure your reverse proxy correctly? Note that with the latest version, the configuration has changed, since the api and web socket endpoints are no longer needed.

About the login page, I will look at how to implement it.

**Comment by tobsowo** [comment]
I use nginx proxy manager.

The application is on a Proxmox CT and nginx proxy manager handles the proxy.
