### ISSUE TITLE
[Feature] Configure CPU threads being used

### ISSUE THREAD

**Issue by zroug** [pluja/whishper#28]
Currently, transcription uses only 4 CPU cores, which is a fraction of the available cores. I think if all cores were used, a significant speedup could be achieved until GPU acceleration is supported.

**Comment by pluja** [comment]
I'll look into it

**Comment by liferadioat** [comment]
Any news to this possibility?

**Comment by pluja** [comment]
Added in [v3.1.2](https://github.com/pluja/whishper/releases/tag/v3.1.2)

**Comment by liferadioat** [comment]
Thanks, I´ve added `CPU_THREADS=24` to my .env, stopped my dockers by `docker compose down` and started it again, but this setting has no impact. What could be wrong here? The latest version was downloaded:
```
Using default tag: latest
latest: Pulling from pluja/whishper
Digest: sha256:429603b542955140aa47cd3ecb071d0335864a9bbf8a61befa984896c8832741
Status: Image is up to date for pluja/whishper:latest
docker.io/pluja/whishper:latest
```

**Comment by pluja** [comment]
@liferadioat I'll check this out later. It was working for me when I tested before pushing. Maybe there's something else.
