### ISSUE TITLE
[BUG] can't get docker-compose to run

### ISSUE THREAD

**Issue by d2a-raudenaerde** [pluja/whishper#31]
I get this error in the logs:
```
whisper-libretranslate  | PermissionError: [Errno 13] Permission denied: '/home/libretranslate/.local/share/argos-translate' 
whisper-libretranslate exited with code 1
```
The status of the images:
```
docker ps                                                                                                                                                                         (base) 
CONTAINER ID   IMAGE                                     COMMAND                  CREATED              STATUS                          PORTS       NAMES
d4b14c62d055   pluja/whishper-frontend:latest            "docker-entrypoint.s…"   About a minute ago   Up 39 seconds                   3000/tcp    whishper-web
2475b66d560b   libretranslate/libretranslate:latest      "./venv/bin/libretra…"   About a minute ago   Restarting (1) 25 seconds ago               whisper-libretranslate
7b7c360a0665   mongo                                     "docker-entrypoint.s…"   About a minute ago   Up About a minute (healthy)     27017/tcp   temp-mongo-1
6bce4a6c69fd   pluja/whishper-transcription-api:latest   "python3 main.py"        About a minute ago   Up About a minute (healthy)     8000/tcp    whisper-api
```

Also the nginx is not available on http://localhost:8082

`docker logs temp-nginx-1 ` returns an empty result.

**Comment by pluja** [comment]
hi, are you using a modified version of the provided compose file? If not, how did you set up whishper? What is your OS?

**Comment by pearlythepirate** [comment]
It's a permissions issue, solved here: https://github.com/pluja/whishper/issues/16#issuecomment-1700483111
`chown -R 1032:1032 whishper_data/libretranslate`
should fix it.

**Comment by pluja** [comment]
@d2a-raudenaerde can you confirm the `chown` command solved it for you?

**Comment by JanX2** [comment]
I had to run `chown -R 1032:1032 whishper_data/libretranslate` when running in rootless Docker on macOS or I would get these PermissionErrors.

**Comment by grigio** [comment]
> `chown -R 1032:1032 whishper_data/libretranslate`

I confirm it works on Linux
`sudo chown -R 1032:1032 whishper_data/libretranslate`

**Comment by pluja** [comment]
@grigio on Linux this command is needed as stated in the [step 3](https://whishper.net/guides/install/#manual-install) of the manual install, and the [get-whishper.sh](https://github.com/pluja/whishper/blob/main/get-whishper.sh#L102) script. but in MacOS I'm not sure since another user reported it was not needed...

**Comment by JanX2** [comment]
Maybe it's not necessary once you get whishper to run in Docker root. I couldn't and in rootless the command fixed my permission errors. I might be doing something weird. Assume I have no idea what I'm doing. 🙃
