### ISSUE TITLE
[Feature] GPU Support

### ISSUE THREAD

**Issue by Arche151** [pluja/whishper#34]
First of all, thank you so much for gifting us this amazing app, @pluja and I'm sorry if I sound disrespectful, since you already mentioned that GPU support is on the roadmap. 

But I wanted to ask, whether you might be able to give us an ETA or progress status on GPU acceleration?

The reason I'm asking is that I'm currently evaluating waiting for whishper to implement it or to try and implement faster-whisper into the Whisper Web UI [WAAS](https://github.com/schibsted/WAAS) which has GPU support, but is sadly using normal whisper as backend with no faster-whisper transition in sight.

I'd be thankful for any kind of information :)

**Comment by pluja** [comment]
Hi, I have implemented everything that's needed for this to work, I Just need to test it a bit more before pushing an update

**Comment by Arche151** [comment]
Thank you for the quick reply and yayy, that's great news! I'm super excited :)

**Comment by pluja** [comment]
I hope this will be available between today and tomorrow, I just need to fix the docker builds for ARM64 (maybe I'll skip this until I'm able to find a better way if I see it's taking too long)

**Comment by Arche151** [comment]
Oh damn, that would be the amazing! Out of curiousity, since I'm kind of a noob: Do you mean you're also working on getting GPU acceleration to work on, say, Apples M chips? 

And yeah, skipping ARM64 support for GPU for now if it's gets too tedious sounds like a good idea, but I'm biased since I wanna use GPU acceleration on an RTX graphics card haha.

**Comment by dalgibbard** [comment]
Have been following the beta release changes, and they're looking good on my side (1.3.5-beta and 1.3.5-beta-gpu images with associated changes from the git commit log)
I'm able to process video files through it on Ubuntu 22.04 (specifically, WSL2 on Windows), with the large-v2 model on an RTX4060Ti at roughly 2fps (so, 1min of video takes 30s to process, including translation)

Very exciting :)

**Comment by pluja** [comment]
Hi, GPU support is released:
https://github.com/pluja/whishper/releases/tag/v2.0.0

Right now, images [are being built](https://github.com/pluja/whishper/actions) and will be published in a few minutes. Feel free to test and tell me how it goes. Make sure to check out the [docs](https://whishper.net/guides/gpu/) and the [release page](https://github.com/pluja/whishper/releases/tag/v2.0.0) to upgrade!

**Comment by Arche151** [comment]
> Hi, GPU support is released: https://github.com/pluja/whishper/releases/tag/v2.0.0
> 
> Right now, images [are being built](https://github.com/pluja/whishper/actions) and will be published in a few minutes. Feel free to test and tell me how it goes. Make sure to check out the [docs](https://whishper.net/guides/gpu/) and the [release page](https://github.com/pluja/whishper/releases/tag/v2.0.0) to upgrade!

Dude, you are on fire. Thank you so much! My PC will arrive tomorrow, I will try it out and report back :)

**Comment by vagelim** [comment]
GPU support is working for me with docker running on Ubuntu under WSL.

**Comment by Arche151** [comment]
@pluja Stupid DHL didn't send me my PC yet. Just so you're not wondering, why I haven't reported back yet :)

**Comment by Arche151** [comment]
@pluja The used PC I bought arrived, buut it's broken. I'll provide feedback once I have a replacement :)

**Comment by Arche151** [comment]
> Hi, GPU support is released: https://github.com/pluja/whishper/releases/tag/v2.0.0
> 
> Right now, images [are being built](https://github.com/pluja/whishper/actions) and will be published in a few minutes. Feel free to test and tell me how it goes. Make sure to check out the [docs](https://whishper.net/guides/gpu/) and the [release page](https://github.com/pluja/whishper/releases/tag/v2.0.0) to upgrade!

Heyy, I finally got my new PC (with an RTX 4060 ti) and it works really good! GPU support is seriously a godsend. Thank you for adding it!
