### ISSUE TITLE
[Feature] Able to download new language pairs for translation

### ISSUE THREAD

**Issue by SoftBoil** [pluja/whishper#35]
**Description of the feature you are requesting:**
Language pairs are only downloaded according to the LT_LOAD_ONLY setting when you first start Docker.

**Describe the solution you'd like**
Detect new languages in the env file after restarting the Docker containers?

**Describe alternatives you've considered**
The only way I found to update the languages was to do a complete re-install.

**Comment by pluja** [comment]
This is now solved in the latest release, [check it out here](https://github.com/pluja/whishper/releases/tag/v3.0.0)
