### ISSUE TITLE
[BUG] Can't get Docker containers to start on Linux due to health issue

### ISSUE THREAD

**Issue by Arche151** [pluja/whishper#36]
I'm using Fedora 38 and can't get all Docker containers to start.

When using the script, provided in the Quick Install guide, docker compose up always fails due to whishper-mongo-1 being unhealthy.

```
Starting whishper...
[+] Running 6/6
 ✘ Container whishper-mongo-1        Error                                 0.2s 
 ✔ Container whisper-api             Healthy                               0.6s 
 ✔ Container whisper-libretranslate  Healthy                               0.2s 
 ✔ Container whishper-web            Started                              10.2s 
 ✔ Container whishper-backend        Recre...                              0.1s 
 ✔ Container whishper-nginx-1        Recre...                              0.0s 
dependency failed to start: container whishper-mongo-1 is unhealthy
```

When using the manual install method, provided in the documentation, docker compose up also always fails, but this time even worse unfortunately, due to whishper-mongo-1  as well as whisper-libretranslate.

```
[admin@fedora Whishper]$ sudo docker compose up -d
[+] Running 6/6
 ✘ Container whisper-libretranslate  Error                                10.3s 
 ✘ Container whishper-mongo-1        Error                                 0.1s 
 ✔ Container whisper-api             Healthy                               0.7s 
 ✔ Container whishper-web            Started                              10.2s 
 ✔ Container whishper-backend        Recre...                              0.1s 
 ✔ Container whishper-nginx-1        Recre...                              0.1s 
dependency failed to start: container whishper-mongo-1 is unhealthy
```

:(

**Comment by Arche151** [comment]
I am using Docker Compose version v2.21.0 which is included in Docker now. So I'm using docker compose, not docker-compose.

I checked the logs and it appears to be an issue with my CPU.

```
WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
  see https://jira.mongodb.org/browse/SERVER-54407
  see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
  see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814

/usr/local/bin/docker-entrypoint.sh: line 416:    28 Illegal instruction     (core dumped) "${mongodHackedArgs[@]}" --fork
```

the logs for libretranslate show no errors but that doesn't really seem to matter since only mongo crashes when using the Quick Install method. And maybe libretranslate crashing during the Manual install method is related to the issue with mongo?

And sorry, I should have checked the logs before!

**Comment by pluja** [comment]
yes! your system does not support AVX and mongo needs AVX in order to work. To solve this issue, please take a look at the docs here:
https://whishper.net/troubleshooting/avx-problems/
