### ISSUE TITLE
[BUG] Can't transcribe on Mac due to permission error

### ISSUE THREAD

**Issue by Arche151** [pluja/whishper#37]
I installed Whispher via the manual install method, as provided in the documentation, on my MacOS due to the Quick Install failing unfortunately.

But every time I try to transcribe something, Whishpers UI shows an error and the Docker logs indicate a permission error:

`PermissionError: [Errno 1] Operation not permitted: '/app/models/faster-whisper-tiny'`

Does someone know a possible fix?

**Comment by pluja** [comment]
Can you try running: `chown -R 1032:1032 whishper_data/libretranslate` inside the project folder?

**Comment by Arche151** [comment]
I did, but now I need to use `sudo` to run docker compose up and then the process fails due to whisper-libretranslate being unhealthy

**Comment by Arche151** [comment]
I did, but now I need to use sudo to run docker compose up and then the process fails due to whisper-libretranslate being unhealthy. The logs for libretranslate show PermissionError: [Errno 13] Permission denied: '/home/libretranslate/.local/share/argos-translate

I think changing the permissions made the problem worse, because before at least Whispher started. And the permission error seemed to be related to the models directory and not libretranslate.

Do you maybe know how to revert chown -R 1032:1032 whishper_data/libretranslate and how I could troubleshoot the models directory permission error? :)

**Comment by pluja** [comment]
you can just remove the `whishper_data` folder if you haven't used it yet or there is no data you need to save

**Comment by Arche151** [comment]
> you can just remove the `whishper_data` folder if you haven't used it yet or there is no data you need to save

Eyy, that did it. It works on my Mac now and is amazing! Thank you!!
