### ISSUE TITLE
Setup for MongoDB doesn’t seem to use existing user

### ISSUE THREAD

**Issue by JanX2** [pluja/whishper#39]
I was trying to debug the MongoDB connection issues that were being logged in my setup. Looks like the DB user “whishper” is never created on a new install and this results in connection errors. I have modified the default .env file to use “root” as the user and now everything is up and running.

**Comment by pluja** [comment]
Hi, I'm unable to reproduce. I just tried with a fresh installation on Linux and everything worked fine, can you explain how did you install Whishper and where?

**Comment by JanX2** [comment]
I installed HEAD on macOS using the method from the docs modified as described in #25.

**Comment by pluja** [comment]
Hi @JanX2 sorry for the late reply. I am closing this since it seems you managed to solve the issue. Also, feel free to try the latest v3 verision.
