### ISSUE TITLE
[BUG] Translation error causes forever unfinished translation

### ISSUE THREAD

**Issue by magicvince** [pluja/whishper#54]
I Launch a new translation, (the original subtitle from transcrbe is ok)

But after many hours the animation  is rolling on "waiting for translation".

If I reboot my computer, whishper still on "waiting for translation" (from spanish to french… but I tried before on another movie and it worked.

**Comment by pluja** [comment]
Are you running on the latest v3 version?

**Comment by magicvince** [comment]
I don't know how I can't  get info about the version.
I install whishper by following step by step the tutorial on the main whishper's site

**Comment by pluja** [comment]
Ok, did you do that recently?

**Comment by magicvince** [comment]
Maximum two days before

**Comment by magicvince** [comment]
Precisely, I install whishper 23/11/23 at 0:55 (france)
 I can launch other jobs but this one never ending
![image](https://github.com/pluja/whishper/assets/627273/305b2b48-d757-4c0b-8dc0-153c8765f313)

**Comment by pluja** [comment]
It seems that there was some kind of bug with the translation, if you want to get rid of that line, you can just remove the whole database. To do that, follow these steps:

1. Stop all the containers: `docker compose down`
2. Remove the database: `sudo rm -rf whishper_data/db_data`
3. Bring the containers up again: `docker compose up -d`

You will lose any transcriptions you had, so make sure to download them before...

**Comment by magicvince** [comment]
Thank you, it's ok but I have to add sudo power for each command line


   ``` 
   sudo docker compose down
   sudo rm -rf whishper_data/db_data
   sudo docker compose up -d
```
