### ISSUE TITLE
[Feature] More verbose logging

### ISSUE THREAD

**Issue by benwilcock** [pluja/whishper#55]
I'm wondering if it might be possible to obtain further logging output by way of adding a DEBUG_LEVEL environment variable. It's nice to be able to see in the docker logs that the services have started, but it would be really useful to be able to also see when events such as translations start and stop, or when automated downloads are in progress.

**Comment by pluja** [comment]
You have all the logs in `whishper_data/logs` folder, can you check it and tell me if that is what you were looking for?

**Comment by pluja** [comment]
I am closing this issue for now, if this is not what you were looking for, please feel free to reopen
