### ISSUE TITLE
Help to run the older web-whisper script

### ISSUE THREAD

**Issue by codernerds** [pluja/whishper#67]
Hi there! 

Firstly, congratulations for this amazing work of yours!

I happen to use an older version of your web-whisper script, and I would like a simpler and more straightforward way to launch the docker containers for the front-end and back-end on port 80, on a VPS server, because I have difficulties getting them to run. Please can you help? I need the working code to run both images, like this example: docker run -p 3000:80 web-whisper for front-end, and the code for the back-end as well. I'm talking about the older web-whisper script below:

https://codeberg.org/pluja/web-whisper#user-content-features
https://codeberg.org/pluja/web-whisper/wiki/Self-Hosting

Best Regards

**Comment by pluja** [comment]
Is there any particular reason you are running the old version?

**Comment by codernerds** [comment]
Wow, what a fast reply!
Yes, the reason is that I like it's layout simplicity, and would like to experiment with it further. I've already found a great forked one that looks a lot like your script, but I would like to run yours also to compare the features and speed. That's it. :-)

**Comment by pluja** [comment]
I'm happy you were able to solve the problem. 

I encourage you to try the newer version! It works better in many aspects, it is simpler to selfhost and it supports large-v3 model. Also the subtitle editor is very useful to quickly edit the transcriptions :)
