### ISSUE TITLE
Confusing!

### ISSUE THREAD

**Issue by radhakrisri** [pluja/whishper#8]
The description on the website https://whishper.net/ says "Open-source, local-first audio transcription and subtitling suite with a simple web UI."

The description on github repo https://github.com/pluja/whishper says "it is a frontend for OpenAI's Whisper, but with batteries included!". 

Will Whishper require connectivity to Open AI to function? In which case, it is not necessarily local?

What does self hosting mean? Will whisper the Open AI model, (not Whispher) run on a local system? 

A system diagram that depicts the various entities, I think, will definitely help.

**Comment by pluja** [comment]
Well, the whisper model is from OpenAI, but it is 100% open source, hence "OpenAI's Whisper". It runs 100% locally, it is stated in the features, it can work offline once models are downloaded.

**Comment by pluja** [comment]
Just edited the description. I hope it is now more clear.
