### ISSUE TITLE
How to install v4

### ISSUE THREAD

**Issue by garanda21** [pluja/whishper#90]
I wanna try new v4 version, but seems that `docker-compose.yml` on that branch only installs `libretranslate`, is there any specific instructions for this v4 ?

**Comment by pluja** [comment]
Hi @garanda21 the v4 is not ready for production yet, so it's not documented / recommended to test/selfhost since many things are left to do.

However, you can selfhost and test the WhisperX-API that will be used in this new version:

https://github.com/pluja/whishper/blob/v4/whisperx-api/README.md
